Product.create!([
  {name: "Yoda sleeping bag", description: "For real", price: "40.0", image_url: "https://staticdelivery.nexusmods.com/mods/1151/images/12353-0-1461721930.png"},
  {name: "Bag of Marbles", description: "A very, very large bag of marbles. You'll be shocked at how large this bag of marbles is.", price: "150.0", image_url: "https://i.pinimg.com/originals/ce/06/38/ce063802cfedf33272e301b1217401bc.jpg"},
  {name: "Asbestos", description: "An antique item from our secret warehouse. Very retro!", price: "30.0", image_url: "https://media.gettyimages.com/photos/asbestos-fiber-picture-id172388720?s=612x612"},
  {name: "Nuclear Waste", description: "We have several barrels in our secret warehouse that need a new loving home!", price: "25.0", image_url: "https://cdn-images-1.medium.com/max/2400/1*l9v61EHZD6CaQnJ8FoNfAQ.jpeg"},
  {name: "DnD Dice set", description: "Take down mighty dragons with this timeless set of 20 sided wonders", price: "507.99", image_url: "https://s-media-cache-ak0.pinimg.com/736x/9c/15/7b/9c157bea5331463f9c539cbce739a4b8.jpg"},
  {name: "Fried Cheese", description: "Cheese and oil subjected to heat", price: "30.0", image_url: "https://cdn.cdkitchen.com/recipes/images/2014/05/113420-3472-mx.jpg"},
  {name: "Hitchhiker's Guide to the Galaxy", description: "In many of the more relaxed civilizations on the Outer Eastern Rim of the Galaxy, the Hitch-Hiker's Guide has already supplanted the great Encyclopaedia Galactica as the standard repository of all knowledge and wisdom, for though it has many omissions and contains much that is apocryphal, or at least wildly inaccurate, it scores over the older, more pedestrian work in two important respects. First, it is slightly cheaper; and secondly it has the words DON'T PANIC inscribed in large friendly letters on its cover.", price: "420.0", image_url: "http://www.notcot.com/images/guide.gif"},
  {name: "Lightsaber", description: "Part laser, part samurai sword, all awesome. The lightsaber is an elegant weapon for a more civilized age, not nearly as clumsy as a blaster", price: "2700.0", image_url: "http://25.media.tumblr.com/d2456964024018fd930338c099371104/tumblr_n2m73lTx2Q1svn82uo1_400.gif"},
  {name: "One Hundred Thousand Bananas", description: "Bananas...lots of bananas. 100,000 of them.", price: "25000.0", image_url: "https://www.yerepouni-news.com/wp-content/uploads/2014/04/banana-banner.jpg"}
])
